name: Build and run tests on pull request v2

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run_test_suite_v3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        rm -rf build
        mkdir build
        cd build/
        cmake ..
        cmake --build .
        
    - name: Run Test Suite
      working-directory: ${{github.workspace}}/build
      run: ./tests

